version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/content"
    schedule:
      interval: "weekly"
