name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Install template
      run: dotnet new --install .
    - name: Create and validate test project
      run: |
        dotnet new aocday --year 2015 --title "Test Puzzle" -o Day01
        cp ./.editorconfig ./Day01/.editorconfig
        cd Day01
        dotnet restore
        dotnet build --no-restore
        dotnet format --verify-no-changes --no-restore
